### ISSUE TITLE
Communication with Processing

### ISSUE THREAD

**Issue by solargroove** [jpbellona/simpleKinect#2]
Hi Jon, 

I managed to route simpleKinect to max/msp using your FAQ and I can read the sensor's values just fine, but when I try to make it communicate with Processing through osc, I am getting values such as fff, i, etc. instead of numbers in the context window. (see attached image) Could you enlighten me on the proper way to make simpleKinect talk to processing? I am running 10.8 and only the stand alone app will work for me. I think your app is fantastic and would very much like to trigger events in processing with it. Thank you very much.

![capture d ecran 2016-02-29 a 20 36 24](https://cloud.githubusercontent.com/assets/17559267/13415493/5c90b518-df29-11e5-926f-834d4ada2da3.png)

**Comment by jpbellona** [comment]
OscP5 library has some great examples. The fff or i or s messages are "typetags" or letting you know the datatype (f = float, i = int, s = string). In Processing, we need to check the type before assigning it to a variable (so a string isn't stored into a float variable).

Try this for printing out values and testing typetags first before getting the values. Check out oscP5 examples for help with specific functions related to OSC messages.
void oscEvent(OscMessage theOscMessage) {
  /* check if theOscMessage has the address pattern we are looking for. */
  if (theOscMessage.checkAddrPattern("/test")==true) {
    /* check if the typetag is the right one. */
    if (theOscMessage.checkTypetag("i")) {
      /* parse theOscMessage and extract the values from the osc message arguments. */
      theOscMessageValue = theOscMessage.get(0).intValue();
      println("OSC value: " + theOscMessageValue);
    }
  }
  
  //print the address pattern for determing parsing information
  println("### received an osc message.");
  println("Address pattern: " + theOscMessage.addrPattern() + " and Type Tag: " + theOscMessage.typetag());
}
