### ISSUE TITLE
Failed to run the PDE

### ISSUE THREAD

**Issue by enzyme69** [jpbellona/simpleKinect#3]
![screen shot 2016-09-19 at 19 57 17](https://cloud.githubusercontent.com/assets/3952687/18628395/5c2be9c0-7ea3-11e6-9620-b8faf749c5a2.png)

I keep getting highlighted error:
       ((Textfield)cp5.controller("inputip")).setFocus(false);

The function controller(String) does not exist.

**Comment by ghost** [comment]
Same error over here!

**Comment by jpbellona** [comment]
This is due to the library controlP5.  This library needs to be version 2.0.4.  I haven't been able to update this to the new controlP5 library. Older P5 libraries can be found here: https://code.google.com/p/controlp5/downloads/list

**Comment by jpbellona** [comment]
Merged version with update for this library.   cp5.getController() instead of cp5.controller()
Should be current.
